### ISSUE TITLE
warnings compiling vmmon on kernel 6.2-rc2

### ISSUE THREAD

**Issue by xevilstar** [vmware/.github#23]
### Describe the bug

In file included from /tmp/modconfig-bkTSUb/vmmon-only/./include/cpu_types.h:29,
                 from /tmp/modconfig-bkTSUb/vmmon-only/./include/modulecall.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/common/moduleloop.c:33:
/tmp/modconfig-bkTSUb/vmmon-only/./include/vm_basic_defs.h:779: warning: "DO_ONCE" redefined
  779 | #define DO_ONCE(code)                                                   \
      | 
In file included from ./include/linux/prandom.h:12,
                 from ./include/linux/random.h:153,
                 from ./include/linux/nodemask.h:97,
                 from ./include/linux/sched.h:23,
                 from /tmp/modconfig-bkTSUb/vmmon-only/common/moduleloop.c:31:
./include/linux/once.h:46: note: this is the location of the previous definition
   46 | #define DO_ONCE(func, ...)                                                   \
      | 
In file included from /tmp/modconfig-bkTSUb/vmmon-only/./include/cpu_types.h:29,
                 from /tmp/modconfig-bkTSUb/vmmon-only/./include/modulecall.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/common/vmx86.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/common/vmx86.c:38:
/tmp/modconfig-bkTSUb/vmmon-only/./include/vm_basic_defs.h:779: warning: "DO_ONCE" redefined
  779 | #define DO_ONCE(code)                                                   \
      | 
In file included from ./include/linux/prandom.h:12,
                 from ./include/linux/random.h:153,
                 from ./include/linux/nodemask.h:97,
                 from ./include/linux/sched.h:23,
                 from /tmp/modconfig-bkTSUb/vmmon-only/common/vmx86.c:31:
./include/linux/once.h:46: note: this is the location of the previous definition
   46 | #define DO_ONCE(func, ...)                                                   \
      | 
In file included from /tmp/modconfig-bkTSUb/vmmon-only/./include/cpu_types.h:29,
                 from /tmp/modconfig-bkTSUb/vmmon-only/./include/modulecall.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/linux/hostif.c:58:
/tmp/modconfig-bkTSUb/vmmon-only/./include/vm_basic_defs.h:779: warning: "DO_ONCE" redefined
  779 | #define DO_ONCE(code)                                                   \
      | 
```
In file included from ./include/linux/prandom.h:12,
                 from ./include/linux/random.h:153,
                 from ./include/linux/nodemask.h:97,
                 from ./include/linux/sched.h:23,
                 from ./include/linux/binfmts.h:5,
                 from /tmp/modconfig-bkTSUb/vmmon-only/linux/hostif.c:31:
./include/linux/once.h:46: note: this is the location of the previous definition
   46 | #define DO_ONCE(func, ...)                                                   \
      | 
  CC [M]  /tmp/modconfig-bkTSUb/vmmon-only/bootstrap/monLoaderVmmon.o
  CC [M]  /tmp/modconfig-bkTSUb/vmmon-only/bootstrap/vmmblob.o
In file included from /tmp/modconfig-bkTSUb/vmmon-only/./include/cpu_types.h:29,
                 from /tmp/modconfig-bkTSUb/vmmon-only/./include/modulecall.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/./common/vmx86.h:33,
                 from /tmp/modconfig-bkTSUb/vmmon-only/linux/driver.h:32,
                 from /tmp/modconfig-bkTSUb/vmmon-only/linux/driver.c:47:
/tmp/modconfig-bkTSUb/vmmon-only/./include/vm_basic_defs.h:779: warning: "DO_ONCE" redefined
  779 | #define DO_ONCE(code)                                                   \
      | 
In file included from ./include/linux/prandom.h:12,
                 from ./include/linux/random.h:153,
                 from ./include/linux/nodemask.h:97,
                 from ./include/linux/list_lru.h:12,
                 from ./include/linux/fs.h:13,
                 from ./include/linux/highmem.h:5,
                 from /tmp/modconfig-bkTSUb/vmmon-only/linux/driver.c:25:
./include/linux/once.h:46: note: this is the location of the previous definition
   46 | #define DO_ONCE(func, ...)                                                   \
      | 
/tmp/modconfig-bkTSUb/vmmon-only/common/task.o: warning: objtool: .text: unexpected end of section

```

### Reproduction steps

1. on debian compile the deb kernel packages ` nice make -j`nproc` bindeb-pkg`
2. install the headers and libc debs first and then the image an image debug ones
3. reboot
4. vmware-modconfig --console --install-all
...

### Expected behavior

the source compiles cleanly without warnings

### Additional context

```
oot@ghost:~# uname -a                                
Linux ghost 6.2.0-rc2 #1 SMP PREEMPT_DYNAMIC Tue Jan  3 09:06:34 CET 2023 x86_64 GNU/Linux
root@ghost:~# gcc --version
gcc (Debian 12.2.0-13) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ghost:~# ld --version
GNU ld (GNU Binutils for Debian) 2.39.90.20230104
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

root@ghost:~# cat /etc/debian_version 
bookworm/sid
```

**Comment by xevilstar** [comment]
[vmmon.tar.zip](https://github.com/vmware/.github/files/10367921/vmmon.tar.zip)

**Comment by markpeek** [comment]
This issue had already been reported and fixed internally.

**Comment by markpeek** [comment]
Thanks for the issue.

**Comment by xevilstar** [comment]
> Thanks for the issue.

where can I get the fixed sources ?
